stmp:
  host: smtp.163.com
  from_addr: 111@163.com
  password: 111
  to_addr: 111@163.com

sync:
  status: true
  time: 86400
  search_day: 7
  search_size: 100
  auto_del: false
  container_path: [
        '/mnt/movies/',
        '/mnt/series/',
        '/mnt/anime/'
    ]

check:
  status: true
  time: 60
  log: true

wechat:
  corp_id:
  secret:
  agent_id:
  to_user:

